### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by rafaelfranca** [SebastianSzturo/basecamp-desktop#3]
What is the License of this software? 
http://choosealicense.com/

Or if you don't intent to have a license make sure you understand the implications of that http://choosealicense.com/no-license/

**Comment by SebastianSzturo** [comment]
Thank you for the issue! I added the MIT Licence to the project. a5ae21b

**Comment by rafaelfranca** [comment]
Thank you for the project and making it available :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
